spring:
  application:
    name: sec-kill
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sec-kill?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Tomato-123
  redis:
    host: localhost
    password: Tomato-123
    port: 6379
  kafka:
    consumer:
      group-id: test
      auto-offset-reset: earliest
mybatis:
  mapper-locations: classpath:mapper/*.xml